### ISSUE TITLE
Веса модели

### ISSUE THREAD

**Issue by AnnaLebedeva** [adeshkin/khakas_russian_translator#1]
Василий, добрый день! Подскажите, есть ли у вас готовые веса получившейся модели? Я пишу магистерский диплом тоже по русскому-хакасскому, хотела сравнить модели на одном тестсете.

**Comment by adeshkin** [comment]
@AnnaLebedeva Добрый день! Веса этих моделей не сохранились. Можем мы созвониться насчет данных и моделей, которые вы используете? Я планирую в следующем году защитить магистерский диплом на физтехе, сейчас планирую собрать собственный датасет
